# Generated by Django 2.2.dev20180517144303 on 2018-05-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyuhaksik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cafe_name',
            field=models.CharField(choices=[('SC', '학생식당'), ('PC', '교직원식당'), ('NPC', '신교직원식당'), ('NSC', '신학생식당'), ('D1', '제1 생활관'), ('D2', '제2 f활관'), ('HP', '행원파크')], max_length=30),
        ),
    ]
