# Generated by Django 2.2.dev20180517144303 on 2018-05-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyuhaksik', '0002_auto_20180523_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
